### ISSUE TITLE
No Deploy :(

### ISSUE THREAD

**Issue by npgockel** [postboot/postboot.org#1]
![image](https://user-images.githubusercontent.com/60376598/88361822-31bf5080-cd2f-11ea-8fc5-7af41855beda.png)

**Comment by KenWilliams74** [comment]
Github pages is probably easiest since it isn't an SSH key.

**Comment by KenWilliams74** [comment]
This is the simplest instructions I've found for it
https://medium.com/mobile-web-dev/how-to-build-and-deploy-a-react-app-to-github-pages-in-less-than-5-minutes-d6c4ffd30f14

**Comment by npgockel** [comment]
But what if we want a database for some reason?

**Comment by KenWilliams74** [comment]
TNT

**Comment by npgockel** [comment]
It's dynamite.
